"""Initial migration

Revision ID: 6c5a1c7d38c1
Revises: 
Create Date: 2024-12-18 15:42:13.201064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c5a1c7d38c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_per_10_minutes', sa.Integer(), nullable=False),
    sa.Column('total_parking_slots', sa.Integer(), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disabled_vehicle_recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('entry_recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('exit_recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('illegal_parking_vehicle_recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('light_vehicle_recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('light_vehicle_recognition', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('illegal_parking_vehicle_recognition', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('exit_recognition', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('entry_recognition', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('disabled_vehicle_recognition', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    op.drop_table('setting')
    # ### end Alembic commands ###
